FROM alica-work-selectors:build AS build
FROM sha256:3d12a9296b83872257786f5b2abd9c7c54221913aff1dc96c9e7b80d56d99837
COPY --from=build /workspace/apps/hermes-control-adapter/dist/source.js /opt/unify-adapter/dist/source.js
