/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentPrincipal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/{operationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIntegrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUnifiedResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchUnifiedResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUnifiedEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUnifiedNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shadow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["compareAuthoritativeOwners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TruthState: "current" | "stale" | "partial" | "empty" | "unavailable" | "unsupported" | "forbidden" | "failed" | "inconclusive";
        ResourceKind: "framework" | "profile" | "agent" | "provider" | "model" | "project" | "task" | "kanban-board" | "cronjob" | "chat-session" | "chat-message" | "chat-route" | "memory-record" | "catalog-snapshot" | "operation" | "notification";
        ResourceOwner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
        ResourceRef: {
            canonicalId: string;
            kind: "framework" | "profile" | "agent" | "provider" | "model" | "project" | "task" | "kanban-board" | "cronjob" | "chat-session" | "chat-message" | "chat-route" | "memory-record" | "catalog-snapshot" | "operation" | "notification";
            owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
            frameworkId?: string;
            nativeId: string;
            displayLabel?: string;
            sourceVersion?: string;
            /** Format: date-time */
            observedAt: string;
            links?: {
                relation: string;
                canonicalId: string;
            }[];
        };
        Warning: {
            code: string;
            message: string;
        };
        ResponseMeta: {
            requestId: string;
            correlationId: string;
            source: {
                owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                frameworkId?: string;
                adapterId: string;
            };
            sourceStatus: string;
            freshness: "current" | "stale" | "partial" | "empty" | "unavailable" | "unsupported" | "forbidden" | "failed" | "inconclusive";
            /** Format: date-time */
            observedAt?: string;
            /** Format: date-time */
            generatedAt: string;
            warnings: {
                code: string;
                message: string;
            }[];
            page?: {
                nextCursor?: string;
                hasMore: boolean;
            };
        };
        ApiError: {
            code: string;
            message: string;
            requestId: string;
            retryable: boolean;
            target?: {
                canonicalId: string;
                kind: "framework" | "profile" | "agent" | "provider" | "model" | "project" | "task" | "kanban-board" | "cronjob" | "chat-session" | "chat-message" | "chat-route" | "memory-record" | "catalog-snapshot" | "operation" | "notification";
                owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                frameworkId?: string;
                nativeId: string;
                displayLabel?: string;
                sourceVersion?: string;
                /** Format: date-time */
                observedAt: string;
                links?: {
                    relation: string;
                    canonicalId: string;
                }[];
            };
            fields?: {
                field: string;
                reason: string;
            }[];
            policyReasons?: string[];
            evidenceId?: string;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                requestId: string;
                retryable: boolean;
                target?: {
                    canonicalId: string;
                    kind: "framework" | "profile" | "agent" | "provider" | "model" | "project" | "task" | "kanban-board" | "cronjob" | "chat-session" | "chat-message" | "chat-route" | "memory-record" | "catalog-snapshot" | "operation" | "notification";
                    owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                    frameworkId?: string;
                    nativeId: string;
                    displayLabel?: string;
                    sourceVersion?: string;
                    /** Format: date-time */
                    observedAt: string;
                    links?: {
                        relation: string;
                        canonicalId: string;
                    }[];
                };
                fields?: {
                    field: string;
                    reason: string;
                }[];
                policyReasons?: string[];
                evidenceId?: string;
            };
        };
        CapabilityMode: "read" | "validate" | "dry-run" | "execute" | "verify" | "subscribe";
        CapabilityManifest: {
            /** @constant */
            schemaVersion: "1.0";
            adapterId: string;
            adapterVersion: string;
            frameworkId?: string;
            /** Format: date-time */
            observedAt: string;
            capabilities: {
                [key: string]: {
                    supported: boolean;
                    modes?: ("read" | "validate" | "dry-run" | "execute" | "verify" | "subscribe")[];
                    constraints?: {
                        [key: string]: unknown;
                    };
                    reason?: string;
                };
            };
        };
        EventEnvelope: {
            eventId: string;
            sequence: string;
            type: string;
            classification: "durable" | "ephemeral";
            source: {
                owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                frameworkId?: string;
            };
            resource?: {
                canonicalId: string;
                kind: "framework" | "profile" | "agent" | "provider" | "model" | "project" | "task" | "kanban-board" | "cronjob" | "chat-session" | "chat-message" | "chat-route" | "memory-record" | "catalog-snapshot" | "operation" | "notification";
                owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                frameworkId?: string;
                nativeId: string;
                displayLabel?: string;
                sourceVersion?: string;
                /** Format: date-time */
                observedAt: string;
                links?: {
                    relation: string;
                    canonicalId: string;
                }[];
            };
            /** Format: date-time */
            eventTime: string;
            /** Format: date-time */
            receivedTime: string;
            correlationId?: string;
            operationId?: string;
            payload: {
                [key: string]: unknown;
            };
            /** @constant */
            schemaVersion: "1.0";
        };
        OperationState: "pending" | "validated" | "preflighted" | "awaiting_confirmation" | "executing" | "applied" | "verifying" | "verified" | "denied" | "failed" | "inconclusive" | "rolling_back" | "rolled_back" | "rollback_failed";
        Operation: {
            operationId: string;
            operationType: string;
            actorId: string;
            target: {
                canonicalId: string;
                kind: "framework" | "profile" | "agent" | "provider" | "model" | "project" | "task" | "kanban-board" | "cronjob" | "chat-session" | "chat-message" | "chat-route" | "memory-record" | "catalog-snapshot" | "operation" | "notification";
                owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                frameworkId?: string;
                nativeId: string;
                displayLabel?: string;
                sourceVersion?: string;
                /** Format: date-time */
                observedAt: string;
                links?: {
                    relation: string;
                    canonicalId: string;
                }[];
            };
            payloadHash: string;
            mode: "validate" | "dry-run" | "execute" | "verify" | "rollback";
            idempotencyKey: string;
            sourceVersion?: string;
            policyDecision: "pending" | "allowed" | "denied";
            state: "pending" | "validated" | "preflighted" | "awaiting_confirmation" | "executing" | "applied" | "verifying" | "verified" | "denied" | "failed" | "inconclusive" | "rolling_back" | "rolled_back" | "rollback_failed";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            evidenceIds: string[];
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        Principal: {
            userId: string;
            username: string;
            displayName: string;
            roles: string[];
            permissions: string[];
        };
        SessionSummary: {
            id: string;
            userId: string;
            deviceLabel: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: date-time */
            expiresAt: string;
            revokedAt: string | null;
        };
        SessionList: {
            items: {
                id: string;
                userId: string;
                deviceLabel: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                lastSeenAt: string;
                /** Format: date-time */
                expiresAt: string;
                revokedAt: string | null;
            }[];
        };
        Health: {
            status: "ok" | "ready" | "not_ready";
            release: string;
        };
        UnifiedResource: {
            resource: {
                canonicalId: string;
                kind: "framework" | "profile" | "agent" | "provider" | "model" | "project" | "task" | "kanban-board" | "cronjob" | "chat-session" | "chat-message" | "chat-route" | "memory-record" | "catalog-snapshot" | "operation" | "notification";
                owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                frameworkId?: string;
                nativeId: string;
                displayLabel?: string;
                sourceVersion?: string;
                /** Format: date-time */
                observedAt: string;
                links?: {
                    relation: string;
                    canonicalId: string;
                }[];
            };
            truth: "current" | "stale" | "partial" | "empty" | "unavailable" | "unsupported" | "forbidden" | "failed" | "inconclusive";
            /** @constant */
            authoritative: true;
            adapterId: string;
            /** Format: date-time */
            fetchedAt: string;
            title: string;
            searchableText: string;
            data: {
                [key: string]: unknown;
            };
        };
        IntegrationStatus: {
            adapterId: string;
            owners: ("hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway")[];
            status: "current" | "stale" | "partial" | "empty" | "unavailable" | "unsupported" | "forbidden" | "failed" | "inconclusive";
            /** Format: date-time */
            observedAt?: string;
            resourceCount: number;
            warnings: {
                code: string;
                message: string;
            }[];
        };
        IntegrationStatusList: {
            items: {
                adapterId: string;
                owners: ("hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway")[];
                status: "current" | "stale" | "partial" | "empty" | "unavailable" | "unsupported" | "forbidden" | "failed" | "inconclusive";
                /** Format: date-time */
                observedAt?: string;
                resourceCount: number;
                warnings: {
                    code: string;
                    message: string;
                }[];
            }[];
        };
        UnifiedResourceList: {
            items: {
                resource: {
                    canonicalId: string;
                    kind: "framework" | "profile" | "agent" | "provider" | "model" | "project" | "task" | "kanban-board" | "cronjob" | "chat-session" | "chat-message" | "chat-route" | "memory-record" | "catalog-snapshot" | "operation" | "notification";
                    owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                    frameworkId?: string;
                    nativeId: string;
                    displayLabel?: string;
                    sourceVersion?: string;
                    /** Format: date-time */
                    observedAt: string;
                    links?: {
                        relation: string;
                        canonicalId: string;
                    }[];
                };
                truth: "current" | "stale" | "partial" | "empty" | "unavailable" | "unsupported" | "forbidden" | "failed" | "inconclusive";
                /** @constant */
                authoritative: true;
                adapterId: string;
                /** Format: date-time */
                fetchedAt: string;
                title: string;
                searchableText: string;
                data: {
                    [key: string]: unknown;
                };
            }[];
            meta: {
                requestId: string;
                correlationId: string;
                source: {
                    owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                    frameworkId?: string;
                    adapterId: string;
                };
                sourceStatus: string;
                freshness: "current" | "stale" | "partial" | "empty" | "unavailable" | "unsupported" | "forbidden" | "failed" | "inconclusive";
                /** Format: date-time */
                observedAt?: string;
                /** Format: date-time */
                generatedAt: string;
                warnings: {
                    code: string;
                    message: string;
                }[];
                page?: {
                    nextCursor?: string;
                    hasMore: boolean;
                };
            };
        };
        UnifiedSearchHit: {
            resource: {
                resource: {
                    canonicalId: string;
                    kind: "framework" | "profile" | "agent" | "provider" | "model" | "project" | "task" | "kanban-board" | "cronjob" | "chat-session" | "chat-message" | "chat-route" | "memory-record" | "catalog-snapshot" | "operation" | "notification";
                    owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                    frameworkId?: string;
                    nativeId: string;
                    displayLabel?: string;
                    sourceVersion?: string;
                    /** Format: date-time */
                    observedAt: string;
                    links?: {
                        relation: string;
                        canonicalId: string;
                    }[];
                };
                truth: "current" | "stale" | "partial" | "empty" | "unavailable" | "unsupported" | "forbidden" | "failed" | "inconclusive";
                /** @constant */
                authoritative: true;
                adapterId: string;
                /** Format: date-time */
                fetchedAt: string;
                title: string;
                searchableText: string;
                data: {
                    [key: string]: unknown;
                };
            };
            score: number;
            matchedFields: string[];
        };
        UnifiedSearchResults: {
            items: {
                resource: {
                    resource: {
                        canonicalId: string;
                        kind: "framework" | "profile" | "agent" | "provider" | "model" | "project" | "task" | "kanban-board" | "cronjob" | "chat-session" | "chat-message" | "chat-route" | "memory-record" | "catalog-snapshot" | "operation" | "notification";
                        owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                        frameworkId?: string;
                        nativeId: string;
                        displayLabel?: string;
                        sourceVersion?: string;
                        /** Format: date-time */
                        observedAt: string;
                        links?: {
                            relation: string;
                            canonicalId: string;
                        }[];
                    };
                    truth: "current" | "stale" | "partial" | "empty" | "unavailable" | "unsupported" | "forbidden" | "failed" | "inconclusive";
                    /** @constant */
                    authoritative: true;
                    adapterId: string;
                    /** Format: date-time */
                    fetchedAt: string;
                    title: string;
                    searchableText: string;
                    data: {
                        [key: string]: unknown;
                    };
                };
                score: number;
                matchedFields: string[];
            }[];
            meta: {
                requestId: string;
                correlationId: string;
                source: {
                    owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                    frameworkId?: string;
                    adapterId: string;
                };
                sourceStatus: string;
                freshness: "current" | "stale" | "partial" | "empty" | "unavailable" | "unsupported" | "forbidden" | "failed" | "inconclusive";
                /** Format: date-time */
                observedAt?: string;
                /** Format: date-time */
                generatedAt: string;
                warnings: {
                    code: string;
                    message: string;
                }[];
                page?: {
                    nextCursor?: string;
                    hasMore: boolean;
                };
            };
        };
        UnifiedNotification: {
            id: string;
            severity: "info" | "warning" | "error" | "critical";
            title: string;
            body: string;
            source: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
            state: "unread" | "read" | "acknowledged";
            /** Format: date-time */
            createdAt: string;
            resource?: {
                canonicalId: string;
                kind: "framework" | "profile" | "agent" | "provider" | "model" | "project" | "task" | "kanban-board" | "cronjob" | "chat-session" | "chat-message" | "chat-route" | "memory-record" | "catalog-snapshot" | "operation" | "notification";
                owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                frameworkId?: string;
                nativeId: string;
                displayLabel?: string;
                sourceVersion?: string;
                /** Format: date-time */
                observedAt: string;
                links?: {
                    relation: string;
                    canonicalId: string;
                }[];
            };
        };
        UnifiedNotificationList: {
            items: {
                id: string;
                severity: "info" | "warning" | "error" | "critical";
                title: string;
                body: string;
                source: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                state: "unread" | "read" | "acknowledged";
                /** Format: date-time */
                createdAt: string;
                resource?: {
                    canonicalId: string;
                    kind: "framework" | "profile" | "agent" | "provider" | "model" | "project" | "task" | "kanban-board" | "cronjob" | "chat-session" | "chat-message" | "chat-route" | "memory-record" | "catalog-snapshot" | "operation" | "notification";
                    owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                    frameworkId?: string;
                    nativeId: string;
                    displayLabel?: string;
                    sourceVersion?: string;
                    /** Format: date-time */
                    observedAt: string;
                    links?: {
                        relation: string;
                        canonicalId: string;
                    }[];
                };
            }[];
            meta: {
                requestId: string;
                correlationId: string;
                source: {
                    owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                    frameworkId?: string;
                    adapterId: string;
                };
                sourceStatus: string;
                freshness: "current" | "stale" | "partial" | "empty" | "unavailable" | "unsupported" | "forbidden" | "failed" | "inconclusive";
                /** Format: date-time */
                observedAt?: string;
                /** Format: date-time */
                generatedAt: string;
                warnings: {
                    code: string;
                    message: string;
                }[];
                page?: {
                    nextCursor?: string;
                    hasMore: boolean;
                };
            };
        };
        UnifiedEventList: {
            items: {
                eventId: string;
                sequence: string;
                type: string;
                classification: "durable" | "ephemeral";
                source: {
                    owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                    frameworkId?: string;
                };
                resource?: {
                    canonicalId: string;
                    kind: "framework" | "profile" | "agent" | "provider" | "model" | "project" | "task" | "kanban-board" | "cronjob" | "chat-session" | "chat-message" | "chat-route" | "memory-record" | "catalog-snapshot" | "operation" | "notification";
                    owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                    frameworkId?: string;
                    nativeId: string;
                    displayLabel?: string;
                    sourceVersion?: string;
                    /** Format: date-time */
                    observedAt: string;
                    links?: {
                        relation: string;
                        canonicalId: string;
                    }[];
                };
                /** Format: date-time */
                eventTime: string;
                /** Format: date-time */
                receivedTime: string;
                correlationId?: string;
                operationId?: string;
                payload: {
                    [key: string]: unknown;
                };
                /** @constant */
                schemaVersion: "1.0";
            }[];
            meta: {
                requestId: string;
                correlationId: string;
                source: {
                    owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                    frameworkId?: string;
                    adapterId: string;
                };
                sourceStatus: string;
                freshness: "current" | "stale" | "partial" | "empty" | "unavailable" | "unsupported" | "forbidden" | "failed" | "inconclusive";
                /** Format: date-time */
                observedAt?: string;
                /** Format: date-time */
                generatedAt: string;
                warnings: {
                    code: string;
                    message: string;
                }[];
                page?: {
                    nextCursor?: string;
                    hasMore: boolean;
                };
            };
        };
        ShadowComparison: {
            adapterId: string;
            owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
            status: "match" | "mismatch" | "unavailable";
            /** Format: date-time */
            comparedAt: string;
            expectedCount: number;
            actualCount: number;
            missing: string[];
            unexpected: string[];
            changed: string[];
            evidenceHash: string;
        };
        ShadowComparisonList: {
            items: {
                adapterId: string;
                owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                status: "match" | "mismatch" | "unavailable";
                /** Format: date-time */
                comparedAt: string;
                expectedCount: number;
                actualCount: number;
                missing: string[];
                unexpected: string[];
                changed: string[];
                evidenceHash: string;
            }[];
            meta: {
                requestId: string;
                correlationId: string;
                source: {
                    owner: "hermes" | "agency" | "dmm" | "worker" | "chat" | "memory-v4" | "gateway";
                    frameworkId?: string;
                    adapterId: string;
                };
                sourceStatus: string;
                freshness: "current" | "stale" | "partial" | "empty" | "unavailable" | "unsupported" | "forbidden" | "failed" | "inconclusive";
                /** Format: date-time */
                observedAt?: string;
                /** Format: date-time */
                generatedAt: string;
                warnings: {
                    code: string;
                    message: string;
                }[];
                page?: {
                    nextCursor?: string;
                    hasMore: boolean;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Health */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Principal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Principal"];
                };
            };
            /** @description ErrorResponse */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ErrorResponse */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentPrincipal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Principal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Principal"];
                };
            };
            /** @description ErrorResponse */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SessionList */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            /** @description ErrorResponse */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ErrorResponse */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description ErrorResponse */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listIntegrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description IntegrationStatusList */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationStatusList"];
                };
            };
            /** @description ErrorResponse */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listUnifiedResources: {
        parameters: {
            query?: {
                owner?: components["schemas"]["ResourceOwner"];
                kind?: components["schemas"]["ResourceKind"];
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description UnifiedResourceList */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedResourceList"];
                };
            };
            /** @description ErrorResponse */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchUnifiedResources: {
        parameters: {
            query: {
                q: string;
                owner?: components["schemas"]["ResourceOwner"];
                kind?: components["schemas"]["ResourceKind"];
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description UnifiedSearchResults */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedSearchResults"];
                };
            };
            /** @description ErrorResponse */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listUnifiedEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description UnifiedEventList */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedEventList"];
                };
            };
            /** @description ErrorResponse */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listUnifiedNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description UnifiedNotificationList */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnifiedNotificationList"];
                };
            };
            /** @description ErrorResponse */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    compareAuthoritativeOwners: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ShadowComparisonList */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShadowComparisonList"];
                };
            };
            /** @description ErrorResponse */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ErrorResponse */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
